name: 'Deploy Application'
description: 'Deploy Sample Book App service via docker compose'
inputs:
  environment:
    description: 'Environment where to deploy Sample Book APP'
    required: true
runs:
  using: composite
  steps:
    - name: Stopping previous application container
      run: docker compose stop sample-book-app-${{ inputs.environment }}
      shell: bash
    - name: Remove previous application container
      run: docker compose rm sample-book-app-${{ inputs.environment }}
      shell: bash
    - name: Run new application container
      run: docker compose up -d sample-book-app-${{ inputs.environment }}
      shell: bash